### ISSUE TITLE
Railsbench: figure out configuration that's compatible with YJIT, and preferably with other Rubies

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/yjit-bench#30]
Right now Railsbench is weirdly incompatible with everything. Specifically, Bundler can't seem to find the Digest gems - it doesn't think 3.0.1pre exists since it's a default gem of prerelease Ruby. And it can't find digest-3.0.0 to install it even though it's on Rubygems.

Just running bin/rails doesn't work because the Gemfile has to say 3.0.0 (Bundler doesn't thing 3.0.1pre exists) or Ruby will activate the wrong gem first:

~~~
/Users/noah/.rubies/ruby-yjit-metrics-prod/lib/ruby/3.1.0/bundler/runtime.rb:300:in `check_for_activated_spec!': You have already activated digest 3.0.1.pre, but your Gemfile requires digest 3.0.0. Since digest is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports digest as a default gem. (Gem::LoadError)
	from /Users/noah/.rubies/ruby-yjit-metrics-prod/lib/ruby/3.1.0/bundler/runtime.rb:29:in `block in setup'
	from /Users/noah/.rubies/ruby-yjit-metrics-prod/lib/ruby/3.1.0/bundler/spec_set.rb:158:in `each'
	from /Users/noah/.rubies/ruby-yjit-metrics-prod/lib/ruby/3.1.0/bundler/spec_set.rb:158:in `each'
	from /Users/noah/.rubies/ruby-yjit-metrics-prod/lib/ruby/3.1.0/bundler/runtime.rb:24:in `map'
~~~

If 3.0.0 is installed manually (can't do it with bundle), we get a different error that doesn't obviously Google well or have an obvious-to-me cause:

~~~
noah@Noahs-MacBook-Pro-3 railsbench % bundle exec bin/rails console
/Users/noah/.gem/ruby/3.1.0/gems/globalid-0.4.2/lib/global_id/uri/gid.rb:176:in `<module:URI>': uninitialized class variable @@schemes in URI
Did you mean?  scheme_list (NameError)
	from /Users/noah/.gem/ruby/3.1.0/gems/globalid-0.4.2/lib/global_id/uri/gid.rb:6:in `<top (required)>'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	from /Users/noah/.gem/ruby/3.1.0/gems/globalid-0.4.2/lib/global_id/global_id.rb:6:in `<top (required)>'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/noah/.gem/ruby/3.1.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	from /Users/noah/.gem/ruby/3.1.0/gems/globalid-0.4.2/lib/global_id.rb:1:in `<top (required)>'
~~~

I *think* the problem is that digest is still a default gem, but Bundler seems to not have been updated for that. This may be a case where we need to use an older Bundler.

**Comment by noahgibbs** [comment]
So: at a minimum Railsbench needs to use the no-longer-built-in mail gems (e.g. net-imap) to Ruby 3.1+, but not on Ruby 3.0 or lower. That may mean two Gemfile.locks.

Now that we're timing MJIT primarily on Ruby 3.0.2, that makes pre-YJIT Ruby compatibility mandatory rather than nice-to-have.

**Comment by noahgibbs** [comment]
Fixed by https://github.com/Shopify/yjit-bench/pull/31
